site_name: Chat API

nav:
  - About: about.md
  - Contacts: contacts.md
  - Developer Guide: developer.md
  - Releases:
      - 0.1.0: releases/010_contacts.md
 
theme:
  name: material
  palette:
    scheme: default

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format